[colors]
background       = '#f3f3f3'
black            = '#f3f3f3'
blue             = '#644ac9'
cursor           = '#282a36'
cyan             = '#036a96'
foreground       = '#1f1f1f'
green            = '#14710a'
magenta          = '#a3144d'
red              = '#cb3a2a'
tabs             = '#e1e4e8'
tabs-active      = '#c9cdd4'
white            = '#1f1f1f'
yellow           = '#846e15'
dim-black        = '#e6e3d7'
dim-blue         = '#523ba3'
dim-cyan         = '#025479'
dim-foreground   = '#181818'
dim-green        = '#0f5a08'
dim-magenta      = '#82103e'
dim-red          = '#a12e20'
dim-white        = '#181818'
dim-yellow       = '#6b5811'
light-black      = '#928eb6'
light-blue       = '#7862d0'
light-cyan       = '#047fb4'
light-foreground = '#1d1d1d'
light-green      = '#198d0c'
light-magenta    = '#bf185a'
light-red        = '#d74c3d'
light-white      = '#2c2b31'
light-yellow     = '#9e841a'
